Feature #11 modal issues
jaychang99/idea-test pull request #24
Opened 2022-11-17 03:08 UTC by doolim98

Related to #11 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- Modal Component
  - `ResultModal` 제거
  - 재사용이 용이한 `PortalModal` 추가
  - Modal Button animation 추가
- Modal 연결
  - TypeInput 페이지 Modal 변경
  - Login,Register 페이지에 성공/실패 Modal 추가

## 비고
Modal 스타일 및 추가 외에 
- Modal Animation을 위해 motion style에 `rapidVariants` 추가하였음
- TypeInput 페이지에 `isReady` state를 추가하였음
  - `countdown`이 아닌 `isREady` state를 기준으로 게임 시작 상태 확인하도록 변경
  - 이제 coutdown modal에서 확인 버튼을 누를때 바로 게임 시작 상태로 변경됨

2022-11-17 03:19 UTC, xhmxnjxx approved these changes
👍

2022-11-17 03:34 UTC, jaychang99 requested changes

2022-11-17 03:34 UTC, jaychang99 commented on src/pages/Register/index.js
> +      </PortalModal>
상황에 따른 두 모달을 추가해주셔서 감사합니다! 그런데 각 상황에 대해 예외처리를 가 조금 더 세부적이고 (ex: 이메일 형식이 맞지 않습니다, 비밀번호는 8자 이상으로 구성해주세요, 닉네임은 10자 이내여야 합니다 등), 요청 전에 이루어지면 좋을 것 같습니다. 현재 구조상 프론트엔드에서는 input 값 안에 어떠한 값이 들어와도 (길이, 형식 상관없이(특히 이메일)) POST 요청을 보내고 있습니다. 요청을 먼저 보내고 오류가 나고 나서야 유저에게 피드백이 갑니다. POST 요청을 보내는 handleSubmit 함수 안에서 `serverAxios.post` 요청을 보내기 전에 먼저 input 값들의 길이나 일치 여부, 형식 일치 여부를 비교한 후에 일치하지 않으면 아예 post 요청을 보내지 않고, 각 상황에 따라 다른 메시지로 모달을 띄워서 상황을 전달해보는건 어떨까요? 이렇게 요청 전에 프론트 단에서 값들을 먼저 검증한 후 요청을 보내면 백엔드 서버의 요청 부하도 줄일 수 있을 것 같습니다 :)

2022-11-17 03:35 UTC, jaychang99 commented on src/components/TypeInput/index.js
> +import { ModalBody, ModalButton, ModalHeader, ModalIcon, ModalTitle } from "components/PortalModal/style";
`/components/{컴포넌트 이름}/styles.js` 에는 `{컴포넌트 이름}` 컴포넌트에서 쓰이는 styled component  가 들어가는 곳입니다. 그래서 원칙적으로는 `components/{컴포넌트이름}/index.js` 외에서는 불러와서 쓰는 것은 최대한 지양해야 하긴 합니다. 해당 스타일드 컴포넌트가 이 컴포넌트에 한정되어 사용될 것 같으면 `components/TypeInput/styles.js` 에 두고 import  해주시고, 여러 페이지에서 공통적으로 쓰일 것 같으면 `components/common/styles.js` 에 두고  import 해주시면 좋을 것 같습니다.

2022-11-17 03:39 UTC, xhmxnjxx commented on src/pages/Register/index.js
> +      </PortalModal>
로그인 페이지에서 예외 처리는 제가 해보겠습니다!

2022-11-17 03:41 UTC, jaychang99 commented on src/components/TypeInput/index.js
> +import { theme } from "styles/theme";
`theme` 은 매 파일에서 import 해주실 필요가 없습니다. 
`src/App.js` 의 `App` 컴포넌트의 `<ThemeProvider theme={theme} > ... </ThemeProvider> 에서 전역으로 contextAPI 를 통해 theme 내용을 주입하고 있어서 `App` 컴포넌트 하위 컴포넌트에서는 모두 사용할 수 있도록 하고 있습니다. 

emotion 의  styled-component 내부에서는 

```JSX
...
color: ${({ theme }) => theme.color.white};
...
```

또는

```JSX
...
color: ${(props) => props.theme.color.white};
...
```

와 같은 문법으로 theme import 없이도 항시 theme 값들에 접근할 수가 있습니다. (Context 를 통해 App 컴포넌트 하위에 redering 되는 모든 스타일드 컴포넌트에서 theme 값을 자동으로 불러 사용할 수 있도록 하고 있기 때문)

2022-11-17 03:42 UTC, jaychang99 commented on src/pages/Register/index.js
> +      </PortalModal>
앗 @doolim98  님이 요 부분 위에 로그인 부분도 간략히 모달 처리 해주신 것 같던데 그럼 이 형태로 바꾸는 부분에 있어서는  @doolim98 님과 의논하셔서 처리해주시면 될 것 같습니다!

2022-11-17 03:46 UTC, doolim98 commented on src/pages/Register/index.js
> +      </PortalModal>
피드백 감사합니다! input을 요청전에 미리 처리하고, 세부적으로 사용자에게 메시지를 표시하도록 해보겠습니다.

2022-11-17 03:50 UTC, jaychang99 commented on src/components/PortalModal/index.js
> +            >
오 모달에도 간략한 애니메이션이 있으면 좋겠다고 생각햇는데 이 애니메이션 정말 좋은 것 같아요!

2022-11-17 03:50 UTC, jaychang99 commented on src/components/PortalModal/style.js
> +  color: ${props => props.color || theme.color.white};
`color` 값이 주어지면 주어진 값을 사용하고 없으면 `theme.color.white` 를 사용하라는 의도에서 작성하신 코드 같습니다!
좋은 방법인 것 같습니다만, 저도 고민하고 있는 부분이 있어서 말씀드립니다. 
저도 항상 `||` 기호와 `??` 의 사용에 대해 헷갈리는 부분이 있었는데
`||` 기호의 경우 앞의 값이 `falsy`, 즉 0 과 같은 값이 들어와도 뒤쪽 operand 를 반환하는 데 비해
`??` 기호의 경우 앞의 값이 정확히 `null` 또는 `undefined` 여야먄 뒤쪽 operand 를 반환한다고 하네요. 

이 경우 그래서 `??` 가 더 좋을 것 같긴 한데 `color` 값이 `0` 과 같이 들어오는 일은 거의 없을 것 같아서 큰 상관은 없을 것 같아요!

관련해서 이 링크를 참고하시면 좋을 것 같습니다!
https://stackoverflow.com/questions/66883181/difference-between-and-operators

2022-11-17 03:54 UTC, doolim98 commented on src/components/TypeInput/index.js
> +import { ModalBody, ModalButton, ModalHeader, ModalIcon, ModalTitle } from "components/PortalModal/style";
아 style들을 불러와서 사용하지 않는게 일반적이군요. 피드백 감사합니다!
지금 코드들에서 children 에 전달하는 component 들이 모달 내부 스타일이 모달 내부에서만 사용될 스타일이 아닐 것 같아서 `common`에 넣어둘까 합니다.( 버튼, 아이콘 및 텍스트 스타일 등)

2022-11-17 03:59 UTC, doolim98 commented on src/components/TypeInput/index.js
> +import { theme } from "styles/theme";
🧐 기존 코드에서 `theme` props를 어디서 받아오는지 이해를 못해서 저는 그냥 import를 했었는데, `ThemeProvider`가 해주는 거였네요! 불필요한 `theme` import들을 제거하겠습니다.

2022-11-17 04:01 UTC, jaychang99 commented on src/components/TypeInput/index.js
> +import { ModalBody, ModalButton, ModalHeader, ModalIcon, ModalTitle } from "components/PortalModal/style";
넵넵 좋습니다!! 일반적이라기보다는 그냥 저희 프로젝트 자체의 컨벤션에 가까운 것 같아요. 요 부분도 이후에 리팩토링 할 때 저희 팀원들끼리 합의만 된다면 방식을 조절해봐도 좋을 것 같습니다!

2022-11-17 04:02 UTC, jaychang99 commented on src/components/TypeInput/index.js
> +import { theme } from "styles/theme";
앗 네네 ㅋㅋ 감사합니다!!

2022-11-17 04:06 UTC, doolim98 commented on src/components/PortalModal/style.js
> +  color: ${props => props.color || theme.color.white};
꼼꼼한 피드백에 링크까지 감사합니다! 
잘 몰랐었는데 객체에 연산자를 적용할 때 유의해야겠네요. 
`??`로 수정하겠습니다.

2022-11-17 04:25 UTC, jaychang99 commented on src/components/PortalModal/style.js
> +  color: ${props => props.color || theme.color.white};
넵!! 반영 감사합니다!

2022-11-17 04:26 UTC, jaychang99 commented on src/pages/Register/index.js
> +      </PortalModal>
넵 감사합니다!!

2022-11-18 06:59 UTC, doolim98 commented on src/pages/Register/index.js
> +      </PortalModal>
해당 사항은 #27에서 따로 하려고 합니다

2022-11-18 11:03 UTC, jaychang99 commented on src/components/PortalModal/index.js
> +} from "./styles";
요부분은 사실 현재 플젝에는 둘다 섞여 있긴 합니다만, 이후 리팩토링 때 변경을 생각 중입니다.  이 라인의 변경  전처럼 `components/ResultModal/styles` 로 하면 이제 모든 컴포넌트들이 `jsconfig.json` 의 baseUrl` 값인 `src/` 를 기준으로 하여 절대경로로 찾아 들어갑니다. 이는 컴포넌트 파일들을 옮기거나 할 때 혼선을 방지할 수가 있어서, 장점이 있습니다. auto import 를 하신다면 아래처럼 VSCode 의 설정의 `Javascript > Preferences: Import Module Specifier` 에서 설정을 `non-relative` 로 해 주시면 절대경로로 import 가 될 것입니다! 지금 단계에서 아주 중요한 사항은 아니라고 생각합니다!

<img width="799" alt="image" src="https://user-images.githubusercontent.com/86560973/202642050-42e7c1f9-c8d6-4a69-97f6-af5c96801adc.png">

2022-11-18 11:03 UTC, jaychang99 commented on src/components/Timer/style.js
>  import styled from "@emotion/styled/macro";
요 파일도 파일명이 `styles.js` 로 통일되면 좋을 것 같습니다!

2022-11-19 04:02 UTC, doolim98 commented on src/components/PortalModal/index.js
> +} from "./styles";
프로젝트에 `from "./styles"`로 import한 코드들이 조금 보이고, 해당 컴포넌트만 사용한 style이라 생각해서 이렇게 바꾸긴 했었어요. 그럼 일단 절대 경로로 작성하겠습니다!

2022-11-19 04:08 UTC, doolim98 commented on src/components/PortalModal/index.js
> +} from "./styles";
vscode 설정 팁 감사함다

2022-11-19 04:11 UTC, doolim98 commented on src/components/Timer/style.js
>  import styled from "@emotion/styled/macro";
넹

2022-11-19 05:53 UTC, jaychang99 commented on src/pages/Register/index.js
> +      </PortalModal>
넵 양이 많아서 해주신 거처럼 별도 이슈로 처리하는 것도 좋을 것 같습니다 ! 알겠습니다. 본 comment 는 resolve 하겠습니다!

2022-11-19 05:54 UTC, jaychang99 commented on src/components/PortalModal/index.js
> +} from "./styles";
아항 넵넵 감사합니다 언젠가는 한번에 바꾸면 코드 유지보수 측면에서 좋을 것 같습니다 (컴포넌트를 디렉토리 안에서 이리저리 옮겨 다닐 때) 
본 comment 는 resolve 하겠습니다!

2022-11-19 05:56 UTC, jaychang99 approved these changes
LGTM

2022-11-19 05:58 UTC, merged